### PR TITLE
Support RHEL, Alma, Rocky 8,9, Debian 11, 12 and Ubuntu 20.04 and 22.04

### PR DESCRIPTION
**Pull request by traylenator**
#### Pull Request (PR) descriptionSupport declared for:

* RedHat 8 and 9
* Alma 8 and 9.
* Rocky 8 and 9
* Debian 11 and 12
* Ubuntu 20.04 and 22.04

#### This Pull Request (PR) fixes the following issues

* Fixes #2

### CODE REVIEW

**Comment by traylenator** [comment]
Some progress - just pending on new release of beaker-vagrant.

**Comment by rwaffen** [comment]
@traylenator you still workin on that?

**Comment by traylenator** [comment]
@rwaffen yes in principle but I just forced push the wrong branch here.

My memory is that while the vagrant testing was working it then stopped working - I lost interest but I believe its working again now.

**Comment by sahaqaa** [comment]
Hello, please advice, is there any chance to get this PR merged? Thank you.

Looking forward to seeing first release of this module to be released to Forge.

**Comment by traylenator** [comment]
Amazing the tests passed.

Need to look again tomorrow for instance we don't want to add EL7 support.

Final clean up

**Review by rwaffen — APPROVED** [review]

**Pull request merged**
